services:

  api1:
    image: lucasrl55/api-rinha-2026:v1.0
    container_name: api1
    environment:
      PORT: 8081
    mem_limit: 140m
    cpus: 0.45
    ports:
      - "8081:8081"
    volumes:
      - ./centroids.bin:/app/dataset.bin:ro

  api2:
    image: lucasrl55/api-rinha-2026:v1.0
    container_name: api2
    environment:
      PORT: 8082
    mem_limit: 140m
    cpus: 0.45
    ports:
      - "8082:8082"
    volumes:
      - ./centroids.bin:/app/dataset.bin:ro

  loadbalancer:
    image: lucasrl55/lb-rinha-2026:v1.0
    container_name: loadbalancer
    ports:
      - "9999:9999"
    mem_limit: 70m
    cpus: 0.1
    depends_on:
      - api1
      - api2
